name: platform_channels_demo
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.7.0
description: A comprehensive demonstration of Flutter platform channels for communication between Flutter and native code.
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
  very_good_analysis: ^7.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
